/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpscaleRouteImport } from './routes/upscale'
import { Route as SegmentRouteImport } from './routes/segment'
import { Route as ResizeImageRouteImport } from './routes/resize-image'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'

const UpscaleRoute = UpscaleRouteImport.update({
  id: '/upscale',
  path: '/upscale',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentRoute = SegmentRouteImport.update({
  id: '/segment',
  path: '/segment',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizeImageRoute = ResizeImageRouteImport.update({
  id: '/resize-image',
  path: '/resize-image',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/resize-image': typeof ResizeImageRoute
  '/segment': typeof SegmentRoute
  '/upscale': typeof UpscaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/resize-image': typeof ResizeImageRoute
  '/segment': typeof SegmentRoute
  '/upscale': typeof UpscaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/resize-image': typeof ResizeImageRoute
  '/segment': typeof SegmentRoute
  '/upscale': typeof UpscaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit'
    | '/history'
    | '/jobs'
    | '/resize-image'
    | '/segment'
    | '/upscale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit'
    | '/history'
    | '/jobs'
    | '/resize-image'
    | '/segment'
    | '/upscale'
  id:
    | '__root__'
    | '/'
    | '/edit'
    | '/history'
    | '/jobs'
    | '/resize-image'
    | '/segment'
    | '/upscale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  HistoryRoute: typeof HistoryRoute
  JobsRoute: typeof JobsRoute
  ResizeImageRoute: typeof ResizeImageRoute
  SegmentRoute: typeof SegmentRoute
  UpscaleRoute: typeof UpscaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upscale': {
      id: '/upscale'
      path: '/upscale'
      fullPath: '/upscale'
      preLoaderRoute: typeof UpscaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segment': {
      id: '/segment'
      path: '/segment'
      fullPath: '/segment'
      preLoaderRoute: typeof SegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize-image': {
      id: '/resize-image'
      path: '/resize-image'
      fullPath: '/resize-image'
      preLoaderRoute: typeof ResizeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  HistoryRoute: HistoryRoute,
  JobsRoute: JobsRoute,
  ResizeImageRoute: ResizeImageRoute,
  SegmentRoute: SegmentRoute,
  UpscaleRoute: UpscaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
